// Cockpit — mock session data
window.SESSIONS = [
  {
    id: 's_47a2',
    project: 'acme-api',
    name: 'refactor auth middleware',
    model: 'opus-4.7',
    state: 'running',
    tool: 'Bash',
    elapsed: '02:14',
    toolsUsed: 14,
    todos: 5,
    todosDone: 2,
    cost: 0.42,
    logs: [
      { t: 'muted', v: '$ pnpm test auth.spec.ts' },
      { t: 'plain', v: ' RUN  src/middleware/auth.spec.ts' },
      { t: 'ok',    v: ' PASS  validates bearer tokens (18ms)' },
      { t: 'ok',    v: ' PASS  rejects expired jwt (4ms)' },
      { t: 'ok',    v: ' PASS  refresh token rotation (22ms)' },
      { t: 'plain', v: ' RUNS  handles concurrent requests' },
      { t: 'muted', v: ' › executing assertion...' },
    ],
  },
  {
    id: 's_91ef',
    project: 'monorepo',
    name: 'migrate packages to vitest',
    model: 'sonnet-5',
    state: 'tool',
    tool: 'Edit',
    elapsed: '04:38',
    toolsUsed: 28,
    todos: 8,
    todosDone: 4,
    cost: 0.18,
    editPath: 'packages/core/vitest.config.ts',
    diff: [
      { type: 'ctx', ln: '12', txt: "export default defineConfig({" },
      { type: 'del', ln: '13', txt: "  test: { environment: 'node' }," },
      { type: 'add', ln: '13', txt: "  test: {" },
      { type: 'add', ln: '14', txt: "    environment: 'happy-dom'," },
      { type: 'add', ln: '15', txt: "    globals: true," },
      { type: 'add', ln: '16', txt: "    setupFiles: ['./test/setup.ts']," },
      { type: 'add', ln: '17', txt: "  }," },
      { type: 'ctx', ln: '18', txt: "  resolve: { alias: {" },
    ],
  },
  {
    id: 's_2bf1',
    project: 'dashboard',
    name: 'add dark mode toggle',
    model: 'opus-4.7',
    state: 'approval',
    tool: 'Bash',
    elapsed: '01:02',
    toolsUsed: 7,
    todos: 4,
    todosDone: 3,
    cost: 0.07,
    approvalTool: 'Bash',
    approvalArgs: {
      command: 'rm -rf node_modules && pnpm install --frozen-lockfile',
      cwd: '~/code/dashboard',
      timeout: 120000,
    },
  },
  {
    id: 's_f03c',
    project: 'scraper',
    name: 'crawl product catalog',
    model: 'sonnet-5',
    state: 'error',
    tool: 'WebFetch',
    elapsed: '00:47',
    toolsUsed: 3,
    todos: 2,
    todosDone: 0,
    cost: 0.03,
    error: 'ECONNREFUSED — upstream api.shop.local:8443 unreachable after 3 retries. Circuit breaker open.',
    retryIn: 8,
  },
  {
    id: 's_c1d9',
    project: 'infra',
    name: 'provision staging cluster',
    model: 'opus-4.7',
    state: 'idle',
    tool: null,
    elapsed: '—',
    toolsUsed: 22,
    todos: 6,
    todosDone: 2,
    cost: 0.91,
    todoList: [
      { status: 'done',   text: 'audit existing terraform modules' },
      { status: 'done',   text: 'write vpc + subnet config' },
      { status: 'active', text: 'configure eks node groups' },
      { status: 'todo',   text: 'set up rds postgres replica' },
      { status: 'todo',   text: 'wire up cloudwatch alarms' },
      { status: 'todo',   text: 'validate with terraform plan' },
    ],
  },
  {
    id: 's_78aa',
    project: 'acme-web',
    name: 'improve LCP on product pages',
    model: 'sonnet-5',
    state: 'done',
    tool: null,
    elapsed: '12:41',
    toolsUsed: 41,
    todos: 7,
    todosDone: 7,
    cost: 1.24,
    summary: 'Reduced LCP from 3.1s → 1.6s by preloading hero image, inlining critical CSS, and deferring the analytics bundle.',
    artifacts: ['PR #2847', 'lighthouse.json', 'perf-report.md'],
  },
];

window.MCP_SERVERS = [
  { id: 'gh',      name: 'github',        desc: 'github.com/modelcontextprotocol', status: 'on',  tools: 14, active: true },
  { id: 'linear',  name: 'linear',        desc: 'linear.app workspace',             status: 'on',  tools: 8 },
  { id: 'sentry',  name: 'sentry',        desc: 'sentry.io/acme',                    status: 'on',  tools: 6 },
  { id: 'pg',      name: 'postgres',      desc: 'staging replica · ro',             status: 'on',  tools: 4 },
  { id: 'fs',      name: 'filesystem',    desc: '~/code',                            status: 'on',  tools: 11 },
  { id: 'slack',   name: 'slack',         desc: 'acme.slack.com',                    status: 'off', tools: 5 },
  { id: 'fig',     name: 'figma',         desc: 'figma.com/files',                   status: 'err', tools: 0 },
  { id: 'browser', name: 'browser',       desc: 'playwright-controlled',             status: 'on',  tools: 9 },
];

window.CMDK_ITEMS = [
  { group: 'Sessions', name: 'acme-api · refactor auth middleware', sub: 's_47a2', state: 'running', arrow: '→ open' },
  { group: 'Sessions', name: 'monorepo · migrate packages to vitest', sub: 's_91ef', state: 'tool', arrow: '→ open' },
  { group: 'Sessions', name: 'dashboard · add dark mode toggle', sub: 's_2bf1', state: 'approval', arrow: '→ open' },
  { group: 'Sessions', name: 'scraper · crawl product catalog', sub: 's_f03c', state: 'error', arrow: '→ open' },
  { group: 'Sessions', name: 'infra · provision staging cluster', sub: 's_c1d9', state: 'idle', arrow: '→ open' },
  { group: 'Sessions', name: 'acme-web · improve LCP', sub: 's_78aa', state: 'done', arrow: '→ open' },

  { group: 'Actions', name: 'New session', sub: '⌘N', ico: '+', arrow: '↵' },
  { group: 'Actions', name: 'Kill selected session', sub: '⌘⌫', ico: '×', arrow: '↵' },
  { group: 'Actions', name: 'Pause all running', sub: '⌘.', ico: '||', arrow: '↵' },
  { group: 'Actions', name: 'Fork session', sub: '⌘F', ico: 'ƒ', arrow: '↵' },
  { group: 'Actions', name: 'Rename session', sub: '⌘R', ico: 'ab', arrow: '↵' },
  { group: 'Actions', name: 'Tag session', sub: '#', ico: '#', arrow: '↵' },
  { group: 'Actions', name: 'Open in terminal', sub: '⌘T', ico: '›_', arrow: '↵' },
  { group: 'Actions', name: 'Approve pending tool call', sub: '⌘↵', ico: '✓', arrow: '↵' },

  { group: 'Navigate', name: 'Sessions',    sub: '⌘1', ico: '▦', arrow: '→' },
  { group: 'Navigate', name: 'Projects',    sub: '⌘2', ico: '▤', arrow: '→' },
  { group: 'Navigate', name: 'History',     sub: '⌘3', ico: '↻', arrow: '→' },
  { group: 'Navigate', name: 'Skills',      sub: '⌘4', ico: '◇', arrow: '→' },
  { group: 'Navigate', name: 'MCP servers', sub: '⌘5', ico: '◈', arrow: '→' },
  { group: 'Navigate', name: 'Plugins',     sub: '⌘6', ico: '◉', arrow: '→' },
  { group: 'Navigate', name: 'Hooks',       sub: '⌘7', ico: '⌥', arrow: '→' },
  { group: 'Navigate', name: 'Settings',    sub: '⌘,', ico: '⚙', arrow: '→' },

  { group: 'Theme', name: 'Toggle dark / light', sub: '⌘⇧L', ico: '◐', arrow: '↵' },
  { group: 'Theme', name: 'Density: compact', sub: '', ico: '—', arrow: '↵' },
  { group: 'Theme', name: 'Density: cozy', sub: '', ico: '≡', arrow: '↵' },
];

// Sample cost-over-time (per-minute bars) for the focus view
window.COST_BARS = [0.02,0.01,0.03,0.02,0.04,0.06,0.05,0.03,0.04,0.07,0.09,0.06,0.05,0.08,0.04,0.06,0.08,0.11,0.09,0.07,0.05,0.08,0.12,0.10];
